// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8AM9icBNaXYrKErPr1LQfZKMEgnf2h8',
    appId: '1:483648490647:web:24cfdd04293bbc312bedd2',
    messagingSenderId: '483648490647',
    projectId: 'project-126d3e3a-ac48-4376-898',
    authDomain: 'project-126d3e3a-ac48-4376-898.firebaseapp.com',
    storageBucket: 'project-126d3e3a-ac48-4376-898.firebasestorage.app',
    measurementId: 'G-PX5GRQGL56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhX3p3j397ovrcTLrGM68CDaxExjGkYk0',
    appId: '1:483648490647:android:2d1ec986606a58662bedd2',
    messagingSenderId: '483648490647',
    projectId: 'project-126d3e3a-ac48-4376-898',
    storageBucket: 'project-126d3e3a-ac48-4376-898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HBy8YCnVkba6zRZRyERB7Pdw8mOLSvs',
    appId: '1:483648490647:ios:74da733e759b8f8d2bedd2',
    messagingSenderId: '483648490647',
    projectId: 'project-126d3e3a-ac48-4376-898',
    storageBucket: 'project-126d3e3a-ac48-4376-898.firebasestorage.app',
    androidClientId: '483648490647-m6cgoiooct48b3mbjh71ufa0dfr6bog0.apps.googleusercontent.com',
    iosClientId: '483648490647-1eie5lt4ddg4mfh83pr4skgmqihf404v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HBy8YCnVkba6zRZRyERB7Pdw8mOLSvs',
    appId: '1:483648490647:ios:74da733e759b8f8d2bedd2',
    messagingSenderId: '483648490647',
    projectId: 'project-126d3e3a-ac48-4376-898',
    storageBucket: 'project-126d3e3a-ac48-4376-898.firebasestorage.app',
    androidClientId: '483648490647-m6cgoiooct48b3mbjh71ufa0dfr6bog0.apps.googleusercontent.com',
    iosClientId: '483648490647-1eie5lt4ddg4mfh83pr4skgmqihf404v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8AM9icBNaXYrKErPr1LQfZKMEgnf2h8',
    appId: '1:483648490647:web:3ce90893e82256682bedd2',
    messagingSenderId: '483648490647',
    projectId: 'project-126d3e3a-ac48-4376-898',
    authDomain: 'project-126d3e3a-ac48-4376-898.firebaseapp.com',
    storageBucket: 'project-126d3e3a-ac48-4376-898.firebasestorage.app',
    measurementId: 'G-K2QMZN7DNE',
  );
}
